import { Resend } from 'resend';

const resend = process.env.RESEND_API_KEY
  ? new Resend(process.env.RESEND_API_KEY)
  : null;

export async function sendAlert(
  to: string,
  subject: string,
  html: string
) {
  if (!resend) {
    console.warn('RESEND_API_KEY missing');
    return;
  }

  if (!process.env.ALERT_FROM_EMAIL) {
    console.warn('ALERT_FROM_EMAIL missing');
    return;
  }

  try {
    const result = await resend.emails.send({
      from: process.env.ALERT_FROM_EMAIL,
      to,
      subject,
      html,
    });

    console.log('Email sent:', result.data?.id);
  } catch (error) {
    console.error('Email send failed:', error);
  }
}

export function buildChangeEmail(params: {
  competitor: string;
  sourceType: string;
  sourceUrl: string;
  summary: string;
  diff: string;
}) {
  return `
  <div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:24px;">
    
    <h1 style="margin-bottom:8px;">
      RivalSense Alert
    </h1>

    <p style="color:#666;">
      A monitored competitor source has changed.
    </p>

    <hr />

    <h2>${params.competitor}</h2>

    <p>
      <strong>Source Type:</strong>
      ${params.sourceType}
    </p>

    <p>
      <strong>Source URL:</strong><br/>
      <a href="${params.sourceUrl}">
        ${params.sourceUrl}
      </a>
    </p>

    <h3>Summary</h3>

    <div
      style="
        background:#f8fafc;
        border:1px solid #e5e7eb;
        padding:16px;
        border-radius:8px;
      "
    >
      ${params.summary}
    </div>

    <h3 style="margin-top:24px;">
      Diff Excerpt
    </h3>

    <pre
      style="
        background:#111827;
        color:#f9fafb;
        padding:16px;
        border-radius:8px;
        overflow:auto;
        white-space:pre-wrap;
      "
    >
${params.diff.slice(0, 3000)}
    </pre>

    <p style="margin-top:24px;color:#666;">
      Generated by RivalSense
    </p>

  </div>
  `;
}
