import type { SeedSourceType } from './aiCompanyUniverse';

export type HistoricIntelligenceSeed = {
  title: string;
  summary: string;
  strategicInsight: string;
  category: string;
  topics: string[];
  sourceType: SeedSourceType;
  sourceUrl: string;
  daysAgo: number;
  confidenceScore?: number;
};

export const historicIntelligenceSeeds: Record<string, HistoricIntelligenceSeed[]> = {
  OpenAI: [
    {
      title: 'OpenAI pushes GPT-4o into the flagship position',
      summary: 'OpenAI centered its product story around a faster multimodal model and broader consumer usage.',
      strategicInsight: 'The release tightened the gap between consumer chat and developer APIs, making multimodal UX a core moat.',
      category: 'product_launch',
      topics: ['multimodal', 'chatgpt', 'model-launch'],
      sourceType: 'release',
      sourceUrl: 'https://openai.com/index/',
      daysAgo: 420,
      confidenceScore: 0.865,
    },
    {
      title: 'OpenAI adjusts API pricing to improve adoption',
      summary: 'Pricing updates signaled a push to widen developer usage and make more workflows economically viable.',
      strategicInsight: 'A lower-friction pricing structure tends to pull experimentation forward and expand paid usage.',
      category: 'pricing',
      topics: ['pricing', 'api', 'developer-adoption'],
      sourceType: 'pricing',
      sourceUrl: 'https://openai.com/pricing',
      daysAgo: 310,
      confidenceScore: 0.802,
    },
    {
      title: 'OpenAI expands docs and support guidance for teams',
      summary: 'Documentation and help-center coverage broadened around enterprise and platform onboarding.',
      strategicInsight: 'Maturing docs usually reflects a move from early adopters into scaled operational use.',
      category: 'platform_maturity',
      topics: ['docs', 'enterprise', 'support'],
      sourceType: 'docs',
      sourceUrl: 'https://help.openai.com',
      daysAgo: 180,
      confidenceScore: 0.744,
    },
  ],
  Anthropic: [
    {
      title: 'Anthropic ships Claude 3.5 Sonnet with stronger coding performance',
      summary: 'Claude updates emphasized better reasoning and code-generation quality across practical workflows.',
      strategicInsight: 'Code-centric gains keep Anthropic competitive where developer trust and output quality matter most.',
      category: 'product_launch',
      topics: ['claude', 'coding', 'reasoning'],
      sourceType: 'release',
      sourceUrl: 'https://www.anthropic.com/news',
      daysAgo: 390,
      confidenceScore: 0.884,
    },
    {
      title: 'Anthropic tightens developer docs around tool use and prompts',
      summary: 'Documentation updates focused on safe tool use, prompt design, and operational guardrails.',
      strategicInsight: 'Better docs lower onboarding cost for serious teams and reduce support burden as usage scales.',
      category: 'documentation',
      topics: ['docs', 'tool-use', 'safety'],
      sourceType: 'docs',
      sourceUrl: 'https://docs.anthropic.com/en/',
      daysAgo: 250,
      confidenceScore: 0.793,
    },
    {
      title: 'Anthropic refreshes pricing and enterprise positioning',
      summary: 'The pricing page highlighted stronger enterprise adoption and a clearer path from pilot to production.',
      strategicInsight: 'Pricing and packaging changes often reveal which workloads Anthropic wants to own next.',
      category: 'pricing',
      topics: ['pricing', 'enterprise', 'commercial'],
      sourceType: 'pricing',
      sourceUrl: 'https://www.anthropic.com/pricing',
      daysAgo: 140,
      confidenceScore: 0.756,
    },
  ],
  'Google DeepMind': [
    {
      title: 'Google DeepMind highlights Gemini 1.5 as the core platform bet',
      summary: 'DeepMind messaging centered on long-context capability and model quality across the Google stack.',
      strategicInsight: 'Long-context performance creates a differentiated wedge in enterprise research and document workflows.',
      category: 'product_launch',
      topics: ['gemini', 'long-context', 'enterprise'],
      sourceType: 'release',
      sourceUrl: 'https://deepmind.google/discover/blog/',
      daysAgo: 430,
      confidenceScore: 0.852,
    },
    {
      title: 'Google updates AI developer docs and sample workflows',
      summary: 'Docs and developer portal updates made it easier to build and test against Gemini APIs.',
      strategicInsight: 'Developer onboarding is a strong indicator of where Google expects third-party usage to grow.',
      category: 'documentation',
      topics: ['docs', 'developers', 'api'],
      sourceType: 'docs',
      sourceUrl: 'https://ai.google.dev',
      daysAgo: 260,
      confidenceScore: 0.762,
    },
    {
      title: 'Google broadens AI blog coverage across products and releases',
      summary: 'Product blog coverage showed how Gemini was being threaded through multiple Google surfaces.',
      strategicInsight: 'Distribution is Google’s biggest advantage, and the blog feed makes that expansion visible early.',
      category: 'platform_maturity',
      topics: ['distribution', 'blog', 'products'],
      sourceType: 'release',
      sourceUrl: 'https://blog.google/technology/ai/',
      daysAgo: 160,
      confidenceScore: 0.719,
    },
  ],
  Mistral: [
    {
      title: 'Mistral pushes a stronger flagship model into the platform',
      summary: 'Mistral continued to position itself as the fast-moving European alternative for frontier model access.',
      strategicInsight: 'Model quality plus regional positioning is the company’s clearest differentiator in enterprise deals.',
      category: 'product_launch',
      topics: ['mistral', 'model', 'enterprise'],
      sourceType: 'release',
      sourceUrl: 'https://mistral.ai/news/',
      daysAgo: 410,
      confidenceScore: 0.842,
    },
    {
      title: 'Mistral expands console and developer workflow coverage',
      summary: 'The platform console and docs improved the path from account creation to production deployment.',
      strategicInsight: 'Console quality is a proxy for how quickly new developers can turn interest into actual usage.',
      category: 'documentation',
      topics: ['console', 'docs', 'developer-experience'],
      sourceType: 'docs',
      sourceUrl: 'https://console.mistral.ai',
      daysAgo: 240,
      confidenceScore: 0.768,
    },
    {
      title: 'Mistral status and reliability signals become more visible',
      summary: 'Operational and incident pages gave teams more confidence evaluating production readiness.',
      strategicInsight: 'Maturing reliability surfaces are a hint that the platform is being used in serious workflows.',
      category: 'reliability',
      topics: ['status', 'ops', 'production'],
      sourceType: 'incident',
      sourceUrl: 'https://status.mistral.ai',
      daysAgo: 120,
      confidenceScore: 0.701,
    },
  ],
  Cohere: [
    {
      title: 'Cohere leans into enterprise retrieval and command models',
      summary: 'Cohere’s platform narrative stayed centered on retrieval, enterprise fit, and workflow reliability.',
      strategicInsight: 'Cohere’s best chance is owning search-heavy enterprise use cases where quality and control matter.',
      category: 'product_launch',
      topics: ['cohere', 'retrieval', 'enterprise'],
      sourceType: 'release',
      sourceUrl: 'https://cohere.com/blog',
      daysAgo: 405,
      confidenceScore: 0.831,
    },
    {
      title: 'Cohere updates docs for the dashboard and API surface',
      summary: 'The docs surface made it easier to move from experimentation to production integration.',
      strategicInsight: 'Good docs often matter more than raw benchmarks once enterprise procurement gets involved.',
      category: 'documentation',
      topics: ['docs', 'dashboard', 'api'],
      sourceType: 'docs',
      sourceUrl: 'https://dashboard.cohere.com',
      daysAgo: 225,
      confidenceScore: 0.742,
    },
    {
      title: 'Cohere refreshes pricing for broader team adoption',
      summary: 'Pricing clarity improved for teams trying to justify pilots and narrow production budgets.',
      strategicInsight: 'Pricing changes often show where Cohere wants to accelerate commercial conversion.',
      category: 'pricing',
      topics: ['pricing', 'adoption', 'enterprise'],
      sourceType: 'pricing',
      sourceUrl: 'https://cohere.com/pricing',
      daysAgo: 130,
      confidenceScore: 0.723,
    },
  ],
  xAI: [
    {
      title: 'xAI launches Grok as a fast-moving chat and reasoning product',
      summary: 'xAI used its release feed to position Grok as a differentiated consumer and developer offering.',
      strategicInsight: 'Distribution via X and rapid product cadence are the main levers xAI can pull against incumbents.',
      category: 'product_launch',
      topics: ['grok', 'chat', 'reasoning'],
      sourceType: 'release',
      sourceUrl: 'https://x.ai/news',
      daysAgo: 390,
      confidenceScore: 0.828,
    },
    {
      title: 'xAI expands API guidance for developers',
      summary: 'The API docs started to look more like a real developer platform rather than a single-product launch.',
      strategicInsight: 'API maturity is a better signal than hype when measuring whether xAI can build a durable platform.',
      category: 'documentation',
      topics: ['api', 'docs', 'developers'],
      sourceType: 'docs',
      sourceUrl: 'https://x.ai/api',
      daysAgo: 220,
      confidenceScore: 0.741,
    },
    {
      title: 'xAI adds open-source touchpoints for ecosystem growth',
      summary: 'The GitHub presence suggests a push to attract builders and experimenters around the broader stack.',
      strategicInsight: 'Open-source signaling helps xAI recruit attention even before enterprise buying is fully mature.',
      category: 'ecosystem',
      topics: ['github', 'ecosystem', 'open-source'],
      sourceType: 'github',
      sourceUrl: 'https://github.com/xai-org',
      daysAgo: 110,
      confidenceScore: 0.684,
    },
  ],
  Perplexity: [
    {
      title: 'Perplexity expands its answer-first search product',
      summary: 'The blog feed highlighted continued investment in search quality and lightweight research workflows.',
      strategicInsight: 'Perplexity competes on workflow convenience, not just model quality, so product polish matters a lot.',
      category: 'product_launch',
      topics: ['search', 'research', 'product'],
      sourceType: 'release',
      sourceUrl: 'https://www.perplexity.ai/hub/blog',
      daysAgo: 400,
      confidenceScore: 0.836,
    },
    {
      title: 'Perplexity clarifies Pro pricing for power users',
      summary: 'Pricing and packaging made the paid workflow more legible for heavy research users and teams.',
      strategicInsight: 'Clear packaging is essential when the product sits between consumer search and enterprise research.',
      category: 'pricing',
      topics: ['pricing', 'pro', 'research'],
      sourceType: 'pricing',
      sourceUrl: 'https://www.perplexity.ai/pro',
      daysAgo: 215,
      confidenceScore: 0.753,
    },
    {
      title: 'Perplexity improves help-center guidance for onboarding',
      summary: 'Documentation updates reduced friction for new users and helped frame the product as a research assistant.',
      strategicInsight: 'Support content is a sign the company is turning acquisition into repeat use.',
      category: 'documentation',
      topics: ['docs', 'help-center', 'onboarding'],
      sourceType: 'docs',
      sourceUrl: 'https://www.perplexity.ai/hub/help-center',
      daysAgo: 125,
      confidenceScore: 0.707,
    },
  ],
  'Meta AI': [
    {
      title: 'Meta AI makes Llama the center of its open model strategy',
      summary: 'The company kept emphasizing open distribution, community adoption, and downstream ecosystem leverage.',
      strategicInsight: 'Meta’s best advantage is distribution plus a large open-source builder base.',
      category: 'product_launch',
      topics: ['llama', 'open-source', 'distribution'],
      sourceType: 'release',
      sourceUrl: 'https://ai.meta.com/blog',
      daysAgo: 415,
      confidenceScore: 0.851,
    },
    {
      title: 'Meta AI grows the Llama documentation surface',
      summary: 'The Llama docs became more practical for developers moving from research into deployment.',
      strategicInsight: 'Documentation quality is a good indicator of how quickly Meta can translate community buzz into usage.',
      category: 'documentation',
      topics: ['docs', 'llama', 'developers'],
      sourceType: 'docs',
      sourceUrl: 'https://llama.meta.com',
      daysAgo: 210,
      confidenceScore: 0.739,
    },
    {
      title: 'Meta AI broadens research and model releases on GitHub',
      summary: 'Open research artifacts signaled a continued push to make the Meta ecosystem the default open-model home.',
      strategicInsight: 'Open-source release cadence often matters more than a single flagship benchmark win.',
      category: 'ecosystem',
      topics: ['github', 'research', 'open-source'],
      sourceType: 'github',
      sourceUrl: 'https://github.com/facebookresearch',
      daysAgo: 95,
      confidenceScore: 0.716,
    },
  ],
  'Hugging Face': [
    {
      title: 'Hugging Face doubles down on the model hub as the default ecosystem layer',
      summary: 'The platform continued to sit at the center of open model discovery, deployment, and community reuse.',
      strategicInsight: 'HF wins by being the connective tissue between builders, models, and deployment targets.',
      category: 'platform_strategy',
      topics: ['hub', 'open-source', 'ecosystem'],
      sourceType: 'website',
      sourceUrl: 'https://huggingface.co',
      daysAgo: 420,
      confidenceScore: 0.854,
    },
    {
      title: 'Hugging Face improves docs for inference and deployment',
      summary: 'Docs updates made it easier to move from hosted models into repeatable production setups.',
      strategicInsight: 'Better deployment docs help the platform capture revenue after the initial community adoption phase.',
      category: 'documentation',
      topics: ['docs', 'inference', 'deployment'],
      sourceType: 'docs',
      sourceUrl: 'https://huggingface.co/docs',
      daysAgo: 230,
      confidenceScore: 0.763,
    },
    {
      title: 'Hugging Face keeps pricing and status pages visible for production users',
      summary: 'Operational transparency around pricing and incidents helps the company look enterprise-ready.',
      strategicInsight: 'Enterprises often trust visible ops surfaces before they trust performance claims.',
      category: 'reliability',
      topics: ['pricing', 'status', 'enterprise'],
      sourceType: 'incident',
      sourceUrl: 'https://status.huggingface.co',
      daysAgo: 105,
      confidenceScore: 0.706,
    },
  ],
  'Stability AI': [
    {
      title: 'Stability AI pushes Stable Diffusion deeper into platform messaging',
      summary: 'The company continued to frame image generation as a platform, not just a single model family.',
      strategicInsight: 'Platform framing matters when the product is facing intense commoditization pressure.',
      category: 'product_launch',
      topics: ['stability', 'image', 'platform'],
      sourceType: 'release',
      sourceUrl: 'https://stability.ai/news',
      daysAgo: 405,
      confidenceScore: 0.812,
    },
    {
      title: 'Stability AI expands platform docs for builders',
      summary: 'Documentation improvements focused on helping developers ship with fewer integration steps.',
      strategicInsight: 'When a model company invests in docs, it usually wants to turn hobbyist use into product use.',
      category: 'documentation',
      topics: ['docs', 'builders', 'api'],
      sourceType: 'docs',
      sourceUrl: 'https://platform.stability.ai/docs',
      daysAgo: 240,
      confidenceScore: 0.751,
    },
    {
      title: 'Stability AI clarifies platform pricing and service visibility',
      summary: 'Pricing and status surfaces made the platform feel more production-oriented and less experimental.',
      strategicInsight: 'Reliability signals are especially important for a company selling creative infrastructure.',
      category: 'pricing',
      topics: ['pricing', 'status', 'production'],
      sourceType: 'incident',
      sourceUrl: 'https://status.stability.ai',
      daysAgo: 118,
      confidenceScore: 0.692,
    },
  ],
  DeepSeek: [
    {
      title: 'DeepSeek positions its flagship model as a low-cost frontier alternative',
      summary: 'The company emphasized performance efficiency and strong model quality at a lower cost profile.',
      strategicInsight: 'Price-performance is the wedge that can move buyers away from larger incumbents.',
      category: 'product_launch',
      topics: ['deepseek', 'pricing', 'model'],
      sourceType: 'website',
      sourceUrl: 'https://www.deepseek.com',
      daysAgo: 390,
      confidenceScore: 0.823,
    },
    {
      title: 'DeepSeek improves API documentation for integration teams',
      summary: 'Developer docs became more important as teams evaluated the model for application workloads.',
      strategicInsight: 'Clear docs help translate benchmark interest into actual developer trial.',
      category: 'documentation',
      topics: ['docs', 'api', 'developers'],
      sourceType: 'docs',
      sourceUrl: 'https://api-docs.deepseek.com',
      daysAgo: 220,
      confidenceScore: 0.738,
    },
    {
      title: 'DeepSeek publishes pricing guidance for broader adoption',
      summary: 'Pricing visibility made the platform easier to evaluate against other low-cost model providers.',
      strategicInsight: 'When price is the main advantage, packaging clarity is the thing that converts attention into tests.',
      category: 'pricing',
      topics: ['pricing', 'adoption', 'api'],
      sourceType: 'pricing',
      sourceUrl: 'https://www.deepseek.com/pricing',
      daysAgo: 120,
      confidenceScore: 0.694,
    },
  ],
};

export function getHistoricSeedsForCompany(name: string) {
  return historicIntelligenceSeeds[name] || [];
}